feat: records die niet meer in de bron staan verwijderen bij bulk proces
Klantinteractie-Servicesysteem/KISS-Elastic-Sync pull request #18
Opened 2024-07-22 14:18 UTC by felixcicatt

Solves [PZ-292](https://dimpact.atlassian.net/browse/PC-292)

2024-07-23 15:22 UTC, mstokericatt requested changes

2024-07-24 14:23 UTC, felixcicatt commented on src/Kiss.Elastic.Sync/ElasticBulkClient.cs
> +                using var deleteRequest = new HttpRequestMessage(HttpMethod.Delete, "_search/scroll");
Ik heb er nog even nagedacht en denk dat het prima is om de Elasticsearch client te gebruiken voor het ophalen van de bestaande ids. Ik denk dat dit stuk code daardoor beter te volgen en onderhouden is.

2024-07-24 15:05 UTC, felixcicatt commented on src/Kiss.Elastic.Sync/ElasticBulkClient.cs
> +            while (hasNext || existingIds.Count > 0)
Done. Zou je kunnen kijken of het zo duidelijker is?

2024-07-25 08:43 UTC, mstokericatt approved these changes

2024-07-25 08:46 UTC, merged